//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Pret { get; set; }
        public Nullable<bool> Negociabil { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Gasit { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
