//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        public string Titlu { get; set; }
        public string Imagine { get; set; }
        public byte[] Imagine1 { get; set; }
        public string Descriere { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<bool> Solved { get; set; }
        public string Greutate { get; set; }
        public string AdresaExpeditor { get; set; }
        public string AdresaDestinatar { get; set; }
        public string CategorieProdus { get; set; }
        public string Judet { get; set; }
        public string Oras { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual User User { get; set; }
    }
}
